insert into users (name,age) values ('bill', 12);
insert into users (name,age) values ('bill', 12);
insert into users (name,age) values ('bill', 12);
insert into users (name,age) values ('bill', 12);
insert into users (name,age) values ('bill', 12);
  insert into users (name,age) values ('bill', 12);
  insert into users (name,age) values ('bill', 12);
  insert into users (name,age) values ('bill', 12);
  insert into users (name,age) values ('bill', 12);
  insert into users (name,age) values ('bill', 12);
    insert into users (name,age) values ('bill', 12);
    insert into users (name,age) values ('bill', 12);
    insert into users (name,age) values ('bill', 12);
    insert into users (name,age) values ('bill', 12);
    insert into users (name,age) values ('bill', 12);
      insert into users (name,age) values ('bill', 12);
      insert into users (name,age) values ('bill', 12);
      insert into users (name,age) values ('bill', 12);
      insert into users (name,age) values ('bill', 12);
      insert into users (name,age) values ('bill', 12);
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into projects (title, category, funding_goal, start_date, end_date) values ('stuff', 'things', 12000, '12/14/18','12/14/19');
insert into pledges (amount, user_id, project_id) values (1200,1,1);
insert into pledges (amount, user_id, project_id) values (1200,1,1);
insert into pledges (amount, user_id, project_id) values (1200,1,1);
insert into pledges (amount, user_id, project_id) values (1200,1,1);
insert into pledges (amount, user_id, project_id) values (1200,1,1);
  insert into pledges (amount, user_id, project_id) values (1200,1,1);
  insert into pledges (amount, user_id, project_id) values (1200,1,1);
  insert into pledges (amount, user_id, project_id) values (1200,1,1);
  insert into pledges (amount, user_id, project_id) values (1200,1,1);
  insert into pledges (amount, user_id, project_id) values (1200,1,1);
    insert into pledges (amount, user_id, project_id) values (1200,1,1);
    insert into pledges (amount, user_id, project_id) values (1200,1,1);
    insert into pledges (amount, user_id, project_id) values (1200,1,1);
    insert into pledges (amount, user_id, project_id) values (1200,1,1);
    insert into pledges (amount, user_id, project_id) values (1200,1,1);
      insert into pledges (amount, user_id, project_id) values (1200,1,1);
      insert into pledges (amount, user_id, project_id) values (1200,1,1);
      insert into pledges (amount, user_id, project_id) values (1200,1,1);
      insert into pledges (amount, user_id, project_id) values (1200,1,1);
      insert into pledges (amount, user_id, project_id) values (1200,1,1);
        insert into pledges (amount, user_id, project_id) values (1200,1,1);
        insert into pledges (amount, user_id, project_id) values (1200,1,1);
        insert into pledges (amount, user_id, project_id) values (1200,1,1);
        insert into pledges (amount, user_id, project_id) values (1200,1,1);
        insert into pledges (amount, user_id, project_id) values (1200,1,1);
          insert into pledges (amount, user_id, project_id) values (1200,1,1);
          insert into pledges (amount, user_id, project_id) values (1200,1,1);
          insert into pledges (amount, user_id, project_id) values (1200,1,1);
          insert into pledges (amount, user_id, project_id) values (1200,1,1);
          insert into pledges (amount, user_id, project_id) values (1200,1,1);
